-- Run this in the Supabase SQL editor before using the new admin, contact,
-- membership, and payment features.

alter table if exists trustees add column if not exists image text;
alter table if exists leaders add column if not exists image text;
alter table if exists events add column if not exists image text;
alter table if exists news add column if not exists image text;

create table if not exists members (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  call_to_bar_year text,
  practice_area text,
  dues_amount numeric,
  payment_reference text unique,
  payment_status text default 'pending',
  status text default 'pending',
  paid_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamptz default now()
);

alter table members enable row level security;
alter table contact_messages enable row level security;

drop policy if exists "Public can create members" on members;
create policy "Public can create members"
  on members for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Admins can read members" on members;
create policy "Admins can read members"
  on members for select
  to authenticated
  using (true);

drop policy if exists "Public can create contact messages" on contact_messages;
create policy "Public can create contact messages"
  on contact_messages for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Admins can read contact messages" on contact_messages;
create policy "Admins can read contact messages"
  on contact_messages for select
  to authenticated
  using (true);

-- Admin login uses Supabase Auth. Create the first admin user manually in
-- Supabase Authentication, then use the dashboard Settings section to add more.
