-- =====================================================================
-- PLBF — Complete Supabase schema
-- Run this ENTIRE file in the Supabase SQL editor.
-- Safe to re-run: every statement uses IF NOT EXISTS / DROP IF EXISTS.
-- =====================================================================

-- ---------------------------------------------------------------------
-- TABLES — homepage content
-- ---------------------------------------------------------------------

create table if not exists trustees (
  id bigint generated by default as identity primary key,
  name text not null,
  position text not null,
  bio text,
  image text,
  display_order int default 0
);

create table if not exists leaders (
  id bigint generated by default as identity primary key,
  name text not null,
  position text not null,
  image text,
  display_order int default 0
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null,
  category text not null,
  location text not null,
  description text not null,
  image text
);

create table if not exists news (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null,
  category text not null,
  excerpt text not null,
  content text,
  image text
);

-- Backfill image columns for any older installs that predate them.
alter table if exists trustees add column if not exists image text;
alter table if exists leaders add column if not exists image text;
alter table if exists events  add column if not exists image text;
alter table if exists news    add column if not exists image text;

-- ---------------------------------------------------------------------
-- TABLES — members, contact, newsletter
-- ---------------------------------------------------------------------

create table if not exists members (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  call_to_bar_year text,
  practice_area text,
  enrollment_number text,
  dues_amount numeric,
  payment_reference text unique,
  payment_status text default 'pending',
  status text default 'pending',
  paid_at timestamptz,
  created_at timestamptz default now()
);

alter table if exists members add column if not exists enrollment_number text;

create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamptz default now()
);

create table if not exists newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------
-- TABLES — section headings, gallery, videos
-- ---------------------------------------------------------------------

create table if not exists section_headings (
  key text primary key,
  eyebrow text,
  title text not null,
  title_highlight text,
  intro text
);

create table if not exists gallery_items (
  id bigint generated by default as identity primary key,
  title text,
  image text not null,
  caption text,
  display_order int default 0
);

create table if not exists videos (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  description text,
  display_order int default 0
);

-- ---------------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------------

alter table members               enable row level security;
alter table contact_messages      enable row level security;
alter table newsletter_subscribers enable row level security;
alter table section_headings      enable row level security;
alter table gallery_items         enable row level security;
alter table videos                enable row level security;
alter table if exists trustees    enable row level security;
alter table if exists leaders     enable row level security;
alter table if exists events      enable row level security;
alter table if exists news        enable row level security;

-- members
drop policy if exists "Public can create members" on members;
create policy "Public can create members"
  on members for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Admins can read members" on members;
create policy "Admins can read members"
  on members for select
  to authenticated
  using (true);

-- contact_messages
drop policy if exists "Public can create contact messages" on contact_messages;
create policy "Public can create contact messages"
  on contact_messages for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Admins can read contact messages" on contact_messages;
create policy "Admins can read contact messages"
  on contact_messages for select
  to authenticated
  using (true);

-- newsletter_subscribers
drop policy if exists "Public can subscribe to newsletter" on newsletter_subscribers;
create policy "Public can subscribe to newsletter"
  on newsletter_subscribers for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Admins can read newsletter subscribers" on newsletter_subscribers;
create policy "Admins can read newsletter subscribers"
  on newsletter_subscribers for select
  to authenticated
  using (true);

-- section_headings
drop policy if exists "Public can read section headings" on section_headings;
create policy "Public can read section headings"
  on section_headings for select to anon, authenticated using (true);

drop policy if exists "Admins can manage section headings" on section_headings;
create policy "Admins can manage section headings"
  on section_headings for all to authenticated using (true) with check (true);

-- gallery_items
drop policy if exists "Public can read gallery items" on gallery_items;
create policy "Public can read gallery items"
  on gallery_items for select to anon, authenticated using (true);

drop policy if exists "Admins can manage gallery items" on gallery_items;
create policy "Admins can manage gallery items"
  on gallery_items for all to authenticated using (true) with check (true);

-- videos
drop policy if exists "Public can read videos" on videos;
create policy "Public can read videos"
  on videos for select to anon, authenticated using (true);

drop policy if exists "Admins can manage videos" on videos;
create policy "Admins can manage videos"
  on videos for all to authenticated using (true) with check (true);

-- trustees
drop policy if exists "Public can read trustees" on trustees;
create policy "Public can read trustees"
  on trustees for select to anon, authenticated using (true);

drop policy if exists "Admins can manage trustees" on trustees;
create policy "Admins can manage trustees"
  on trustees for all to authenticated using (true) with check (true);

-- leaders
drop policy if exists "Public can read leaders" on leaders;
create policy "Public can read leaders"
  on leaders for select to anon, authenticated using (true);

drop policy if exists "Admins can manage leaders" on leaders;
create policy "Admins can manage leaders"
  on leaders for all to authenticated using (true) with check (true);

-- events
drop policy if exists "Public can read events" on events;
create policy "Public can read events"
  on events for select to anon, authenticated using (true);

drop policy if exists "Admins can manage events" on events;
create policy "Admins can manage events"
  on events for all to authenticated using (true) with check (true);

-- news
drop policy if exists "Public can read news" on news;
create policy "Public can read news"
  on news for select to anon, authenticated using (true);

drop policy if exists "Admins can manage news" on news;
create policy "Admins can manage news"
  on news for all to authenticated using (true) with check (true);

-- =====================================================================
-- IMAGE STORAGE BUCKET
-- Admin image uploads go to a public storage bucket named "images".
-- Without this bucket + these policies, uploads fail silently.
-- =====================================================================

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can read images" on storage.objects;
create policy "Public can read images"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'images');

drop policy if exists "Admins can upload images" on storage.objects;
create policy "Admins can upload images"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'images');

drop policy if exists "Admins can update images" on storage.objects;
create policy "Admins can update images"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'images')
  with check (bucket_id = 'images');

drop policy if exists "Admins can delete images" on storage.objects;
create policy "Admins can delete images"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'images');

-- =====================================================================
-- VIDEO STORAGE BUCKET
-- Admin video uploads go to a public storage bucket named "videos".
-- Without this bucket + these policies, video uploads fail with a
-- generic "storage error" — make sure this block actually runs.
-- =====================================================================

insert into storage.buckets (id, name, public)
values ('videos', 'videos', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can read videos storage" on storage.objects;
create policy "Public can read videos storage"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'videos');

drop policy if exists "Admins can upload videos storage" on storage.objects;
create policy "Admins can upload videos storage"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'videos');

drop policy if exists "Admins can update videos storage" on storage.objects;
create policy "Admins can update videos storage"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'videos')
  with check (bucket_id = 'videos');

drop policy if exists "Admins can delete videos storage" on storage.objects;
create policy "Admins can delete videos storage"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'videos');

-- =====================================================================
-- DONE
-- Admin login uses Supabase Auth. Create the first admin user manually
-- in Supabase Authentication, then use the dashboard Settings section
-- to add more.
-- =====================================================================
